#!/usr/bin/env bash

# Shared .env and generated personal-file helpers for per-user bootstraps.
# This file is intended to be sourced after DOTFILES_DIR has been set.

DOTFILES_ENV_FILE="${DOTFILES_ENV_FILE:-${DOTFILES_DIR:?DOTFILES_DIR must be set}/.env}"
DOTFILES_GENERATED_MARKER_TEXT="Generated by dotfiles bootstrap; rerun bootstrap to update."
DOTFILES_GENERATED_MARKER="# $DOTFILES_GENERATED_MARKER_TEXT"
DOTFILES_GENERATED_LEGACY_MARKER="# Generated by dotfiles bootstrap from .env; rerun bootstrap to update."
DOTFILES_UI_GENERATED_TARGETS=(
  "$HOME/.Xresources"
  "$HOME/.config/gtk-3.0/gtk.css"
  "$HOME/.config/gtk-4.0/gtk.css"
  "$HOME/.config/rofi/config.rasi"
  "$HOME/.config/rofi/theme.rasi"
  "$HOME/.config/dunst/dunstrc"
  "$HOME/.config/alacritty/alacritty.toml"
  "$HOME/.config/picom/picom.conf"
  "$HOME/.config/betterlockscreen/betterlockscreenrc"
)
DOTFILES_REQUIRED_ENV_VARS=(
  DOTFILES_GIT_NAME
  DOTFILES_GIT_EMAIL
  DOTFILES_GTK_DOWNLOADS_DIR
  DOTFILES_GTK_PROJECTS_DIR
)

dotfiles_env_has_assignment() {
  local key=$1

  [[ -f "$DOTFILES_ENV_FILE" ]] || return 1
  grep -Eq "^[[:space:]]*(export[[:space:]]+)?${key}=" "$DOTFILES_ENV_FILE"
}

dotfiles_array_contains() {
  local needle=$1
  shift
  local item

  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done

  return 1
}

load_dotfiles_env() {
  local nounset_enabled=0

  [[ -e "$DOTFILES_ENV_FILE" ]] || return 0
  if [[ ! -f "$DOTFILES_ENV_FILE" ]]; then
    echo "Dotfiles env path is not a regular file: $DOTFILES_ENV_FILE" >&2
    exit 1
  fi

  case $- in
    *u*)
      nounset_enabled=1
      set +u
      ;;
  esac

  # shellcheck disable=SC1090
  if ! source "$DOTFILES_ENV_FILE"; then
    if [[ $nounset_enabled -eq 1 ]]; then
      set -u
    fi
    echo "Could not load dotfiles env file: $DOTFILES_ENV_FILE" >&2
    echo "Use shell-style KEY=value assignments, as shown in .env.example." >&2
    exit 1
  fi

  if [[ $nounset_enabled -eq 1 ]]; then
    set -u
  fi
}

dotfiles_env_value_is_missing() {
  local key=$1

  if [[ ! -v $key ]]; then
    return 0
  fi

  [[ -z "${!key}" ]]
}

prompt_dotfiles_env_value() {
  local key=$1
  local prompt=$2
  local default_value=${3:-}
  local value

  if ! dotfiles_env_value_is_missing "$key"; then
    return 0
  fi

  if [[ ! -t 0 ]]; then
    DOTFILES_MISSING_ENV_VARS+=("$key")
    return 0
  fi

  while :; do
    if [[ -n "$default_value" ]]; then
      printf '%s [%s]: ' "$prompt" "$default_value" >&2
    else
      printf '%s: ' "$prompt" >&2
    fi

    if ! read -r value; then
      echo "No value provided for $key." >&2
      exit 1
    fi

    if [[ -z "$value" && -n "$default_value" ]]; then
      value=$default_value
    fi

    if [[ -n "$value" ]]; then
      printf -v "$key" '%s' "$value"
      DOTFILES_PROMPTED_ENV_VARS+=("$key")
      return 0
    fi

    echo "$key is required." >&2
  done
}

fail_for_missing_dotfiles_env_values() {
  local key

  printf 'Missing required dotfiles env values:' >&2
  for key in "${DOTFILES_MISSING_ENV_VARS[@]}"; do
    printf ' %s' "$key" >&2
  done
  printf '\n' >&2
  echo "Create $DOTFILES_ENV_FILE from .env.example or rerun the bootstrap interactively." >&2
  exit 1
}

validate_dotfiles_env_value() {
  local key=$1

  if [[ "${!key}" == *$'\n'* || "${!key}" == *$'\r'* ]]; then
    echo "$key must be a single-line value." >&2
    exit 1
  fi
}

expand_dotfiles_user_path() {
  local path=$1

  case "$path" in
    \~)
      printf '%s' "$HOME"
      ;;
    \~/*)
      printf '%s/%s' "$HOME" "${path#~/}"
      ;;
    *)
      printf '%s' "$path"
      ;;
  esac
}

normalize_dotfiles_dir_value() {
  local key=$1
  local value

  value="$(expand_dotfiles_user_path "${!key}")"
  if [[ "$value" != /* ]]; then
    echo "$key must be an absolute path or use ~/path: $value" >&2
    exit 1
  fi

  printf -v "$key" '%s' "$value"
}

append_missing_dotfiles_env_assignments() {
  local keys_to_append=()
  local key

  for key in "${DOTFILES_REQUIRED_ENV_VARS[@]}"; do
    if ! dotfiles_env_has_assignment "$key" || dotfiles_array_contains "$key" "${DOTFILES_PROMPTED_ENV_VARS[@]}"; then
      keys_to_append+=("$key")
    fi
  done

  [[ ${#keys_to_append[@]} -gt 0 ]] || return 0

  if [[ ! -e "$DOTFILES_ENV_FILE" ]]; then
    (umask 077 && : > "$DOTFILES_ENV_FILE")
    echo "Created local bootstrap env: $DOTFILES_ENV_FILE"
  elif [[ ! -f "$DOTFILES_ENV_FILE" ]]; then
    echo "Dotfiles env path is not a regular file: $DOTFILES_ENV_FILE" >&2
    exit 1
  fi

  {
    if [[ -s "$DOTFILES_ENV_FILE" ]]; then
      printf '\n'
    else
      printf '# Local dotfiles bootstrap values.\n'
      printf '# Edit this file, then rerun the user bootstrap to regenerate local files.\n\n'
    fi

    for key in "${keys_to_append[@]}"; do
      printf '%s=%q\n' "$key" "${!key}"
    done
  } >> "$DOTFILES_ENV_FILE"

  chmod go-rwx "$DOTFILES_ENV_FILE" 2>/dev/null || true
}

ensure_dotfiles_env_values() {
  DOTFILES_MISSING_ENV_VARS=()
  DOTFILES_PROMPTED_ENV_VARS=()

  load_dotfiles_env
  prompt_dotfiles_env_value DOTFILES_GIT_NAME "Git user.name"
  prompt_dotfiles_env_value DOTFILES_GIT_EMAIL "Git user.email"
  prompt_dotfiles_env_value DOTFILES_GTK_DOWNLOADS_DIR "GTK Downloads bookmark path" "$HOME/Downloads"
  prompt_dotfiles_env_value DOTFILES_GTK_PROJECTS_DIR "GTK Projects bookmark path" "$HOME/projects"

  if [[ ${#DOTFILES_MISSING_ENV_VARS[@]} -gt 0 ]]; then
    fail_for_missing_dotfiles_env_values
  fi

  local key
  for key in "${DOTFILES_REQUIRED_ENV_VARS[@]}"; do
    validate_dotfiles_env_value "$key"
  done

  normalize_dotfiles_dir_value DOTFILES_GTK_DOWNLOADS_DIR
  normalize_dotfiles_dir_value DOTFILES_GTK_PROJECTS_DIR
  append_missing_dotfiles_env_assignments
}

is_dotfiles_generated_target() {
  local target=$1

  [[ ! -L "$target" && -f "$target" ]] || return 1
  grep -Fq "$DOTFILES_GENERATED_MARKER_TEXT" "$target" ||
    grep -Fq "$DOTFILES_GENERATED_LEGACY_MARKER" "$target"
}

backup_or_reject_generated_target() {
  local target=$1
  local backup_dir=$2
  local backup_existing="${BACKUP_EXISTING:-1}"
  local rel_path
  local backup_path
  local backup_parent

  [[ -e "$target" || -L "$target" ]] || return 0
  is_dotfiles_generated_target "$target" && return 0

  if [[ $backup_existing -eq 0 ]]; then
    echo "Existing unmanaged target would conflict: $target" >&2
    echo "Rerun without --no-backup to move conflicts into ~/.dotfiles-bootstrap-backup/." >&2
    exit 1
  fi

  rel_path="${target#"$HOME"/}"
  if [[ "$rel_path" == "$target" ]]; then
    rel_path="$(basename -- "$target")"
  fi
  backup_path="$backup_dir/$rel_path"
  backup_parent="$(dirname -- "$backup_path")"

  mkdir -p "$backup_parent"
  echo "Backing up existing target: $target -> $backup_path"
  mv -- "$target" "$backup_path"
}

backup_or_reject_generated_targets() {
  local backup_dir=$1

  backup_or_reject_generated_target "$HOME/.gitconfig" "$backup_dir"
  backup_or_reject_generated_target "$HOME/.config/gtk-3.0/bookmarks" "$backup_dir"

  local target
  for target in "${DOTFILES_UI_GENERATED_TARGETS[@]}"; do
    backup_or_reject_generated_target "$target" "$backup_dir"
  done
}

write_dotfiles_generated_file() {
  local target=$1
  local tmp_target="${target}.tmp.$$"

  mkdir -p -- "$(dirname -- "$target")"
  cat > "$tmp_target"
  mv -- "$tmp_target" "$target"
}

escape_file_uri_path() {
  local path=$1
  local encoded=""
  local char
  local escaped
  local i
  local LC_ALL=C

  for ((i = 0; i < ${#path}; i++)); do
    char=${path:i:1}
    case "$char" in
      [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._~/-])
        encoded+="$char"
        ;;
      *)
        printf -v escaped '%%%02X' "'$char"
        encoded+="$escaped"
        ;;
    esac
  done

  printf '%s' "$encoded"
}

quote_git_config_value() {
  local value=$1

  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '"%s"' "$value"
}

generate_dotfiles_gitconfig() {
  local backup_dir=$1
  local target="$HOME/.gitconfig"
  local git_name
  local git_email

  git_name="$(quote_git_config_value "$DOTFILES_GIT_NAME")"
  git_email="$(quote_git_config_value "$DOTFILES_GIT_EMAIL")"

  backup_or_reject_generated_target "$target" "$backup_dir"
  write_dotfiles_generated_file "$target" <<EOF
$DOTFILES_GENERATED_MARKER
[user]
	name = $git_name
	email = $git_email
[credential "https://github.com"]
	helper =
	helper = !/usr/bin/gh auth git-credential
[credential "https://gist.github.com"]
	helper =
	helper = !/usr/bin/gh auth git-credential
EOF
}

generate_dotfiles_gtk_bookmarks() {
  local backup_dir=$1
  local target="$HOME/.config/gtk-3.0/bookmarks"
  local downloads_uri_path
  local projects_uri_path

  downloads_uri_path="$(escape_file_uri_path "$DOTFILES_GTK_DOWNLOADS_DIR")"
  projects_uri_path="$(escape_file_uri_path "$DOTFILES_GTK_PROJECTS_DIR")"

  backup_or_reject_generated_target "$target" "$backup_dir"
  write_dotfiles_generated_file "$target" <<EOF
$DOTFILES_GENERATED_MARKER
file://$downloads_uri_path
file://$projects_uri_path
EOF
}

dotfiles_generated_marker_for_style() {
  local style=$1

  case "$style" in
    css|rasi)
      printf '/* %s */\n' "$DOTFILES_GENERATED_MARKER_TEXT"
      ;;
    bang)
      printf '! %s\n' "$DOTFILES_GENERATED_MARKER_TEXT"
      ;;
    hash)
      printf '# %s\n' "$DOTFILES_GENERATED_MARKER_TEXT"
      ;;
    *)
      echo "Unknown generated marker style: $style" >&2
      return 1
      ;;
  esac
}

load_dotfiles_ui_sizes_for_generation() {
  local helper="$DOTFILES_DIR/home/.config/dotfiles/ui-sizes.sh"
  local sizes_file="$DOTFILES_DIR/home/.config/dotfiles/ui-sizes.env"

  if [[ ! -r "$helper" ]]; then
    echo "Missing UI sizes helper: $helper" >&2
    exit 1
  fi
  if [[ ! -r "$sizes_file" ]]; then
    echo "Missing UI sizes config: $sizes_file" >&2
    exit 1
  fi

  DOTFILES_UI_SIZES_FILE="$sizes_file"
  # shellcheck disable=SC1090
  source "$helper"
}

render_dotfiles_ui_template() {
  local template=$1
  local target=$2
  local marker_style=$3

  backup_or_reject_generated_target "$target" "$DOTFILES_UI_BACKUP_DIR"
  write_dotfiles_generated_file "$target" <<EOF
$(dotfiles_generated_marker_for_style "$marker_style")
$(awk '
  {
    line = $0
    for (name in ENVIRON) {
      if (name ~ /^DOTFILES_UI_/) {
        value = ENVIRON[name]
        gsub(/\\/, "\\\\", value)
        gsub(/&/, "\\\\&", value)
        gsub("@" name "@", value, line)
      }
    }
    print line
  }
' "$template")
EOF
}

generate_dotfiles_ui_files() {
  local backup_dir=$1
  local template_dir="$DOTFILES_DIR/home/.config/dotfiles/templates"

  DOTFILES_UI_BACKUP_DIR=$backup_dir
  load_dotfiles_ui_sizes_for_generation

  render_dotfiles_ui_template "$template_dir/Xresources.tmpl" "$HOME/.Xresources" bang
  render_dotfiles_ui_template "$template_dir/gtk-3.0.css.tmpl" "$HOME/.config/gtk-3.0/gtk.css" css
  render_dotfiles_ui_template "$template_dir/gtk-4.0.css.tmpl" "$HOME/.config/gtk-4.0/gtk.css" css
  render_dotfiles_ui_template "$template_dir/rofi-config.rasi.tmpl" "$HOME/.config/rofi/config.rasi" rasi
  render_dotfiles_ui_template "$template_dir/rofi-theme.rasi.tmpl" "$HOME/.config/rofi/theme.rasi" rasi
  render_dotfiles_ui_template "$template_dir/dunst-dunstrc.tmpl" "$HOME/.config/dunst/dunstrc" hash
  render_dotfiles_ui_template "$template_dir/alacritty.toml.tmpl" "$HOME/.config/alacritty/alacritty.toml" hash
  render_dotfiles_ui_template "$template_dir/picom.conf.tmpl" "$HOME/.config/picom/picom.conf" hash
  render_dotfiles_ui_template "$template_dir/betterlockscreenrc.tmpl" "$HOME/.config/betterlockscreen/betterlockscreenrc" hash
}

generate_dotfiles_personal_files() {
  local backup_dir=$1

  generate_dotfiles_gitconfig "$backup_dir"
  generate_dotfiles_gtk_bookmarks "$backup_dir"
  generate_dotfiles_ui_files "$backup_dir"
}
