#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/render-root-ui.sh [--destdir DIR]

Render root-managed UI config files from home/.config/dotfiles/ui-sizes.env.
Use --destdir for non-root verification renders.
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
DESTDIR=/

while (($#)); do
  case "$1" in
    --destdir)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for --destdir" >&2
        exit 2
      fi
      DESTDIR=$2
      shift
      ;;
    --destdir=*)
      DESTDIR=${1#*=}
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

ui_helper="$DOTFILES_DIR/home/.config/dotfiles/ui-sizes.sh"
ui_sizes="$DOTFILES_DIR/home/.config/dotfiles/ui-sizes.env"
if [[ ! -r "$ui_helper" ]]; then
  echo "Missing UI sizes helper: $ui_helper" >&2
  exit 1
fi
if [[ ! -r "$ui_sizes" ]]; then
  echo "Missing UI sizes config: $ui_sizes" >&2
  exit 1
fi

DOTFILES_UI_SIZES_FILE="$ui_sizes"
# shellcheck disable=SC1090
source "$ui_helper"

render_template_to_target() {
  local template=$1
  local target=$2
  local marker_style=$3
  local final_target="${DESTDIR%/}$target"
  local tmp_target

  if [[ ! -r "$template" ]]; then
    echo "Missing root UI template: $template" >&2
    exit 1
  fi

  mkdir -p -- "$(dirname -- "$final_target")"
  tmp_target="$(mktemp --tmpdir="$(dirname -- "$final_target")" ".dotfiles-root-ui.XXXXXX")"

  {
    case "$marker_style" in
      css)
        printf '/* Generated by dotfiles root UI renderer; rerun bootstrap-root.sh --with-lightdm to update. */\n'
        ;;
      hash)
        printf '# Generated by dotfiles root UI renderer; rerun bootstrap-root.sh --with-lightdm to update.\n'
        ;;
      *)
        echo "Unknown marker style: $marker_style" >&2
        rm -f -- "$tmp_target"
        exit 1
        ;;
    esac

    awk '
      {
        line = $0
        for (name in ENVIRON) {
          if (name ~ /^DOTFILES_UI_/) {
            value = ENVIRON[name]
            gsub(/\\/, "\\\\", value)
            gsub(/&/, "\\\\&", value)
            gsub("@" name "@", value, line)
          }
        }
        print line
      }
    ' "$template"
  } > "$tmp_target"

  chmod 0644 "$tmp_target"
  mv -- "$tmp_target" "$final_target"
}

render_template_to_target \
  "$DOTFILES_DIR/root/etc/lightdm/lightdm-gtk-greeter.conf.tmpl" \
  /etc/lightdm/lightdm-gtk-greeter.conf \
  hash

render_template_to_target \
  "$DOTFILES_DIR/root/usr/share/themes/Dotfiles-DarkBlue/gtk-3.0/gtk.css.tmpl" \
  /usr/share/themes/Dotfiles-DarkBlue/gtk-3.0/gtk.css \
  css
